language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
      # Build tags that match this regex in addition to building the master branch.
    - /^v[0-9]+\.[0-9]+/

deploy:
  provider: bintray
  file: bintray.json
  user: "SAvm/xUPiAwJFHzFQ7LXBt8LqWSh9SkBaQb1yk0ybgFxwABEHVhm0oXnXWACnnd6p5mmAQuWf7TjrSPLPb1D6JSBHD8SprFSURKwimbnaAfbqqVr9u1ROYP4Dx6HOG1ABzwOs5Q/D7iYd3Up9rX6kNiF9sr/1Iu86042rZX6EWgN5dMs8y919LgGI0qhMmreTQ0m8YzuHcxVfYVEQFKfjWdjJ+6mtMQ4K8yu2nQLfuK+6OI5TuXS2zhxZt+DWT5yz7NHd3z11lHzkQiuD2J7dyDOxhx9DmK4JeSAXWNmttLAqHL3KKlzjzZjvnW19rKYO034uStgD3nioNevv9PtEB+96lgbmNFt7NcCrVs3VvDPwG22ERdChV+9yEwxudFFpcT6V4ZG8I3MiBLt/4COoSddXeb2xRfDbXR4UVl3s1jQnt6FCwZx8r/iCvxEL4b3X417JOxsfv2/0jAFtGsimBRe5wTF5Gs1rKaE2Z2sKJ17mtsgdD8qi+GwO34y6UtVyXCrr3t+kT8tqia9f9y/mhfhmMgPpuhhpBaQcRDLnJjN9yu6ufWxB6mPEjUiC1Ci1Sqdzzy0OO4LhXtGISoPWiI20OHdcHaEEK9FC/We5eaKYIwarld4HIzZkiqK8OHHpJNNDcEjRa1oJsjZzwa9PASdBZCfbSV/aOFH5zBvbGw="
  key: "Jo5UjTCsGMqYKI9Mp8oCgVhJZIo0HpUS+k+hdH4O9vzUQ8++SXcMOfPGhOWKMP3e6wfoP/qXVW07YyrciPE39woiRuR3J4ynHqT0SwkCsTCMB5c5FNx9MlHS5cSF65pp9XKHxgiCq0bmSI6lzhSFhIfMYA/bRWC6uAyK0EAnhTmEqzozSv5VB7EwmlDM0acCeT5Vg7bcrXSl+NES21UnCPAfjvAi+tQLHA8VR28PO7N7tYJrn7xNyj6REajXAwFGOA7p/zrDQxVa8DwAJJbHXxS2l5Uw9dbqLROjz2JVTccWgmi8UdOeSqsNXEXxbcFiDzKH5WG+TAqjBPYmog8Lz4cgmIttyPaUS8VizwyoaKxVGZSbXQtcf0YSTPcNAQwIF5CICX16VnQMLX81f+4WlMoFkWHgB4q5BB/UD70o3zeVRqHyLPaotG/0mpprF19fn3JMcGsnxOslD6oN/U1psSRQhMV0yWHEAGTqWS5sqLfjZe+RtADIrttyQ7pqLb3CXDnUGaOXgFZABgYIDwggn39iiaJ1vFPuaR9QkY11D04wFofoqBqRIUp8Om0KXxJcdq+jP7RQtBXy4M6xqB3gJeZNfqPPCOY/bvpq9VbgXiMxleD69ZL5XDbuhZFsuyU+sbbmaKuDvKJpqRmVq54/y302n08wcCOLh/hXiYPFlZQ="